meta:
  zones: (( merge ))

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

compilation:
  cloud_properties:
    instance_type: c1.medium
    availability_zone: (( meta.zones.z1 ))

networks: (( merge ))

jobs:
  - name: nats
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(1) ))

  - name: etcd
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(9) ))

  - name: hurler
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(16) ))
