meta: (( merge ))

networks: (( merge ))

releases:
  - name: fake-diego
    version: latest
  - name: cf
    version: latest

jobs:
  - name: nats
    release: cf
    template: nats
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: cf1
        static_ips: (( merge ))
    properties:
      networks: (( meta.networks.z1 ))

  - name: etcd
    release: cf
    template: etcd
    instances: 1
    persistent_disk: 10024
    resource_pool: medium_z1
    networks:
      - name: cf1
        static_ips:  (( merge ))
    properties:
      networks: (( meta.networks.z1 ))

  - name: hurler
    release: fake-diego
    template:
      - hurler
    instances: 1
    resource_pool: small_z1
    networks:
      - name: cf1
        static_ips:  (( merge ))
    properties:
      network_name: cf1

  - name: executor
    release: fake-diego
    template:
      - executor
    instances: 1
    resource_pool: large_z1
    networks:
      - name: cf1
    properties:
      network_name: cf1

  - name: stager
    release: fake-diego
    template:
      - stager
    instances: 1
    resource_pool: small_z1
    networks:
      - name: cf1
    properties:
      network_name: cf1

properties:
  executor:
    memory_capacity_mb: 1000

  etcd:
    machines: (( jobs.etcd.networks.cf1.static_ips ))

  nats:
    machines: (( jobs.nats.networks.cf1.static_ips ))
    port: 4222
    user: (( merge ))
    password: (( merge ))
    use_gnatsd: true

  hurler:
    machine: (( jobs.hurler.networks.cf1.static_ips.[0] ))
